BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Deal_Disconts" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"idDeal"	INTEGER NOT NULL,
	"idDiscont"	INTEGER NOT NULL,
	FOREIGN KEY("idDeal") REFERENCES "Deals"("id"),
	FOREIGN KEY("idDiscont") REFERENCES "Disconts"("id")
);
CREATE TABLE IF NOT EXISTS "Deal_Services" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"idDeal"	INTEGER NOT NULL,
	"idService"	INTEGER NOT NULL,
	"idDiscont"	INTEGER,
	FOREIGN KEY("idDeal") REFERENCES "Deals"("id"),
	FOREIGN KEY("idService") REFERENCES "Services"("id"),
	FOREIGN KEY("idDiscont") REFERENCES "Disconts"("id")
);
CREATE TABLE IF NOT EXISTS "Disconts" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Description"	TEXT,
	"Percent"	REAL,
	"Value"	REAL
);
CREATE TABLE IF NOT EXISTS "Deals" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"idClient"	INTEGER NOT NULL,
	"Total"	REAL NOT NULL,
	"Commission"	REAL NOT NULL,
	"Description"	TEXT,
	FOREIGN KEY("idClient") REFERENCES "Clients"("id")
);
CREATE TABLE IF NOT EXISTS "Services" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Description"	TEXT,
	"Price"	REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS "Clients" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL,
	"Activity"	TEXT,
	"Address"	TEXT,
	"Phone"	TEXT
);
COMMIT;
